; org.xhtmlrenderer.pdf.ITextFontResolver.level=FINER
; xr.util-logging.loggingEnabled=true
; xr.util-logging.handlers=java.util.logging.ConsoleHandler
; xr.util-logging.use-parent-handler=false
; xr.util-logging.java.util.logging.ConsoleHandler.level=ALL
;
; xr.util-logging.org.xhtmlrenderer.level = ALL
; xr.util-logging.org.xhtmlrenderer.config.level = ALL
; xr.util-logging.org.xhtmlrenderer.exception.level = ALL
; xr.util-logging.org.xhtmlrenderer.general.level = ALL
; xr.util-logging.org.xhtmlrenderer.init.level = ALL
; xr.util-logging.org.xhtmlrenderer.load.level = ALL
; xr.util-logging.org.xhtmlrenderer.load.xml-entities.level = ALL
; xr.util-logging.org.xhtmlrenderer.match.level = ALL
; xr.util-logging.org.xhtmlrenderer.cascade.level = ALL
; xr.util-logging.org.xhtmlrenderer.css-parse.level = ALL
; xr.util-logging.org.xhtmlrenderer.layout.level = ALL
; xr.util-logging.org.xhtmlrenderer.render.level = ALL