= Rahul Somasunderam
rahul.som@gmail.com ~ +1-510-449-3467 ~ San Jose, CA, USA
2017-09-17
:sectnums!:
:notoc:
:nofooter:
:jbake-type: page
:jbake-status: published

Developer with lots of experience in Java and Groovy.
Passionate about Functional Programming and Open Source.

== Experience

=== Transcend Insights

_formerly Certify Data Systems_ --
Campbell, CA --
Senior Engineer --
Jul 11 - Present

* Architected _HealthLogix_, the platform for Health Information Exchange
* Built and managed Jenkins Build System and Tools surrounding it
* Simplified deployments for 30+ applications by building out and managing a Kubernetes Cluster
* Sped up onboarding for new developers by automating machine setup using boxen and dotfiles
* Improved test data quality by developing DSLs for authoring content in complex data formats
* Created DSLs for testing intricate workflows, improving test coverage
* Collaborated with partner services for building software that worked with each other
* Developed pre interview assignments for javascript and groovy to make hiring smoother

=== Certify Data Systems

_Employee of Intelliswift Software Inc_ --
San Jose CA --
Java Developer --
Apr 08 - Jul 11

* Developed the Certify Gateway and Certify HealthDock products
* Improved turnaround time for new interfaces by developing Jython API for customization of inbound and outbound messages

=== PRI Network

_Employee of Intelliswift Software Inc_ --
Warrendale PA  --
Java Developer --
Feb 08 - Apr 08

* Implemented several reports for customers to access audits
* Developed a tool to move data across databases with all relational dependencies

=== Infosys Technologies Ltd

Bangalore INDIA --
Software Engineer --
Nov 05 - Jan 08

* Developed reports for compliance and auditing
* Developed COBOL module to let the Business Analysts merge their test data along with the data from several systems into the complex plumbing of modules on the Mainframe
* Developed Java tool to help in static analysis of COBOL code

== Technology

I have been programming since I was 12, starting with trivial programs on logo and basic, and eventually working on several larger applications and some serious, some fun languages

[unstyled]
* **Java & the JVM** - Java, Groovy, Kotlin, Grails, Spring, Hibernate, Gradle
* **Testing** - Spock, Geb, JUnit
* **Databases** - Oracle, MySQL, PostgreSQL, Cassandra
* **Frontend** - Javascript, Objective C, Swift
* **Other** - Asciidoctor, Jenkins, Docker, Kubernetes, Puppet

== Open Source

I frequently contribute to open source projects that I use. I also maintain a few projects of my own.

[unstyled]
* **grooves** - Event Sourcing toolkit for JVM Languages
* **swaggydoc** - Grails 2 Plugin that adds Swagger support to Grails Controllers
* **ihe-iti** - Library for dealing with _Integrating Healthcare in Enterprise_'s IT Infrastructure profiles
* **muval** - Library version of NIST's Meaningful Use validator for Clinical Document Architecture

== Education

=== Bachelor of Technology (Electronics and Communications Engineering)

Pondicherry Engineering College, Pondicherry University, INDIA --
Aug 01 - Apr 05
