= Rahul Somasunderam
rahul.som@gmail.com ~ +1-510-449-3467 ~ San Jose, CA, USA
2024-03-28
:sectnums!:
:notoc:
:nofooter:
:jbake-type: page
:jbake-status: published

Engineer with lots of experience with the JVM, and developer productivity.

== Experience

=== Netflix

Senior Software Engineer --
[.period]#Apr '18 - Present#

* Maintained CI tooling infrastructure, Artifact Storage and Version Control
* Partnered with engineers on other teams to improve their CI experience
* Managed multiple migrations

=== Transcend Insights

Senior Engineer --
[.period]#Jul '11 - Mar '18#

* Architected their Health Information Exchange product
* Built and managed CI/CD system based on Jenkins and Kubernetes
* Worked with partner companies for building software that worked with each other

=== Certify Data Systems

_Employee of Intelliswift Software Inc_ --
Java Developer
[.period]#Apr '08 - Jul '11#

* Developed the Certify Gateway and Certify HealthDock products

=== PRI Network

_Employee of Intelliswift Software Inc_ --
Java Developer
[.period]#Feb '08 - Apr '08#

* Implemented several reports for customers to access audits
* Developed a tool to move selective data across environments with all relational dependencies

=== Infosys Technologies Ltd

Bangalore INDIA --
Software Engineer --
[.period]#Nov '05 - Jan '08#

* Developed reports for compliance and auditing
* Developed COBOL modules to let the Business Analysts merge their test data along with the data from several systems into the complex plumbing of modules on the Mainframe
* Developed Java tool to help in static analysis of COBOL code to facilitate a migration to Java

== Technology

I have been programming since I was 12, starting with trivial programs on logo and basic, and eventually working on several larger applications and some serious, some fun languages

[unstyled]
* **Java & the JVM** - Java, Groovy, Kotlin, Spring, Hibernate, Gradle
* **Testing** - Spock, Geb, JUnit
* **Databases** - Oracle, MySQL, PostgreSQL, Cassandra
* **Frontend** - Javascript, Objective C, Swift

== Education

=== Bachelor of Technology (Electronics and Communications Engineering)

Pondicherry Engineering College, Pondicherry University, INDIA
[.period]#Aug '01 - Apr '05#
