= Rahul Somasunderam
rahul.som@gmail.com ~ +1-510-449-3467 ~ San Jose, CA, USA
2016-09-03
:sectnums!:
:notoc:
:nofooter:
:jbake-type: page
:jbake-status: published

Developer with lots of experience in Java and Groovy.
Passionate about Functional Programming and Open Source.

== Experience

=== Transcend Insights

_formerly Certify Data Systems_ --
Campbell, CA --
Senior Engineer --
Jul 11 - Present

* Architected _HealthLogix_, the platform for Health Information Exchange
* Built a reverse push mechanism for last mile connectivity
* Started and maintained build system
* Automated the setup machines using boxen & puppet
* Dockerized deployment and testing of products
* Created DSLs for authoring content in complex data formats
* Collaborated with several partner services for building software that worked with each other
* Developed pre interview assignments for javascript and groovy to make hiring smoother

=== Certify Data Systems

_Employee of Intelliswift Software Inc_ --
San Jose CA --
Java Developer --
Apr 08 - Jul 11

* Built the Certify Gateway and Certify HealthDock products
* Created a Jython API for runtime customization of inbound messages
* Built a JNLP-Swing client to integrate with Electronic Medical Record (EMR) vendors who needed filesystem based IO

=== PRI Network

_Employee of Intelliswift Software Inc_ --
Warrendale PA  --
Java Developer --
Feb 08 - Apr 08

* Implemented several reports for customers to access audits
* Developed a tool to move data across databases with all dependencies

=== Infosys Technologies Ltd

Bangalore INDIA --
Software Engineer --
Nov 05 - Jan 08

* Developed reports for compliance and auditing
* Developed a COBOL module to let the Business Analysts merge their test data along with the data from several systems into the complex plumbing of modules on the Mainframe
* Developed a tool to help in static analysis of COBOL code

== Technology

I have been programming since I was 12, starting with trivial programs on logo and basic, and eventually working on several larger applications and some serious, some fun languages

Java & the JVM::
  Java, Groovy, Grails, Spring, Hibernate, Gradle
Testing::
  Spock, Geb, JUnit
Databases::
  Oracle, MySQL, PostgreSQL, Cassandra
Frontend::
  Javascript, Objective C, Swift
Other::
  Jenkins, Puppet, Docker, Asciidoctor

== Education

=== Bachelor of Technology (Electronics and Communications Engineering)

Pondicherry Engineering College, Pondicherry University, INDIA --
Aug 01 - Apr 05
