= Fitness Trackers
Rahul Somasunderam
2012-06-25
:jbake-type: post
:jbake-status: published
:jbake-tags: fitness, tracker, bodybugg, fitbit, fuelband, basis
:idprefix:

{nbsp}

The first thing you're taught when you start learning physics is

________________________________________________________
If you can't measure it, you can't do anything about it.
________________________________________________________

[[when-cycling]]
When cycling
+++++++++++

I applied that approach to cycling - I bought a
http://amzn.to/Rk2yTx[Schwinn] computer and then a
http://amzn.to/Rk2KSG[Cateye] and this made me understand my biking
better. I knew
how fast I could go, what my speed was on flats, climbs and descents.
With Schwinn, I had an understanding of
how many calories I burnt. With Cateye, I started looking at my cadence.

[[when-not-cycling]]
When not cycling
+++++++++++++++

However seasonal allergies brought my biking to a halt. And my fitness
started declining again. So I decided to
sign up for a gym membership - I hate using treadmills and stationary
bikes.

________________________________________________________________________
If I'm walking or biking for 5 minutes, I expect to be farther away from
where I started. If I'm not, I get bored.
________________________________________________________________________

However I've come to terms with the fact that, the gym is the only way I
can get back to being fit if I can't
get my miles when pollen is high.

As part of a goodie bag at a race
http://www.active.com/cycling/yountville-ca/napa-valley-tour-de-cure-2012[ride]
I attended this year, I got a
pedometer from the good folks at Walgreens. It's terrible in terms of
accuracy and discreetness. One day, I did
nothing more than driving to work and returning home; and it said I'd
walked 5 miles. And it's noisy; my colleagues thought
I was tin-foil carrying a Geiger Counter with me. Also pedometers don't
account for other activity I do.

[[the-choices]]
The choices
++++++++++

I saw my trainer at the gym wearing one of those
http://www.bodybugg.com/[Bodybuggs]
http://amzn.to/TkthyG[image:https://www.amazon.com/favicon.ico[image,18,18]].
That seemed like a good idea.
Except that you require a subscription to get the best out of it. So
I've started looking at other alternatives

* http://www.fitbit.com/product[Fitbit]
http://amzn.to/WYwUOY[image:https://www.amazon.com/favicon.ico[image,18,18]]
seems to do away with the subscription, but it's just a 3D
accelerometer;
__that's like a fancy pedometer__. It's great in that it has an
http://dev.fitbit.com/[API], and apparently a
thriving ecosystem.
* Then there's Nike's http://www.nike.com/fuelband/[Fuelband]
http://amzn.to/VXo1XY[image:https://www.amazon.com/favicon.ico[image,18,18]]
which looks great, but then doesn't give any meaningful
metrics other than it's own fake currency.
* The third contender is https://mybasis.com/[Basis] which so far seems
to be vaporvare, in that we don't know much
about it except for that it will cost $199.

Here's what I'm looking for in the device:

* Either has either an API or a means to download data to my computer.
* Measures my activity and gives meaningful metrics.
* Lets me look at data in fine grained durations so I can compare past
performance.

[[what-does-it-mean-to-have-an-api]]
What does it mean to have an API?
++++++++++++++++++++++++++++++++

It means that I do not have to pay money to someone so they can gather
up my data, and sell it to someone else. My
fitness data is my Protected Health Information. I don't want to pay
someone $10 a month so they know
when I've been pumping iron and have my information sent to the makers
of
http://www.cytosport.com/products/muscle-milk[Muscle Milk] and when I'm
sleeping on my couch for 3 days in a row,
send it to
http://www.nutrisystem.com/jsps_hmr/home/index.jsp?_requestid=594177[Nutrisystem].
I would love something
like good old Nike+ which merely synced with your iPod and if you chose
to, shared it on their website. However it looks
like everyone is taking the cloud seriously and there aren't any
products in this category that work that way. I may be
wrong here, but that's what everyone's advertising looks like.

Do you have any fitness trackers? What do you like about them? How have
they helped you? Tweet me at http://twitter.com/rahulsom[@rahulsom] or
get me on
http://www.quora.com/Fitness/I-want-a-fitness-health-tracking-device-Whats-my-best-bet[Quora]
