= The year in fitness
Rahul Somasunderam
2013-01-05
:jbake-type: post
:jbake-status: published
:jbake-tags:
:idprefix:

2012 had been a fairly successful year in some aspects. In some, it was
terrible.

[[cycling]]
Cycling
~~~~~~~

I had set a target of 1500 miles and was possibly very very short of
this target. 
A lot of things caused this - mostly my lazyness. However the good news
was that 
I was able to get back to biking after my rather long hiatus after an
accident. 
Also I never did many 50 miles rides. There was just one 50 mile ride.
Most rides 
were shorter, though they included some rides to Palomares.

The best thing however was, I got closer to my ideal weight. I got
better average 
speeds. I expanded my territory, i.e. got into mountain biking. I did
some rides in 
Skyline but several rides at Mission Peak. Also my climb speed has
improved a lot.

For 2013, I want to revive my goal from 2012, i.e. 1500 miles on my road
bike. I 
have signed up for an 80 miler in May. Also 
I want to pack in a few mountain rides. And I want to buy my own
mountain bike. 
I'm looking at the 
http://reviews.mtbr.com/2013-specialized-camber['13 Specialized Camber
29]. 
Any suggestions are welcome.

[[running]]
Running
~~~~~~~

I was able to manage to start running. It took a lot of effort, but I
got comfortable 
with running ~10K. The speed isn't great, but it's still something. For
2013, I'm 
thinking of getting to do a half marathon.

[[otherwise]]
Otherwise
~~~~~~~~~

I took help from a personal trainer to get my shit straight. And that
was helpful. 
If you need help with your fitness goals, do consider consulting a
personal trainer. 
You might think you don't want to hulk up, and that's fine, but having a
trainer who 
knows what the hell they're doing advise you is better than you trying
to figure out 
how to reach your goals.

For 2013, my goal keep this going. As a first hurdle, I seem to have
screwed up my 
wrist, __again__.
