name: Build Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle

      - name: Build with Gradle
        env:
          GRGIT_USER: ${{github.actor}}
          GRGIT_PASS: ${{secrets.GITHUB_TOKEN}}
        run: ./gradlew publish --scan --stacktrace
