name: Build Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle

      - name: Build with Gradle
        env:
          GRGIT_USER: ${{github.actor}}
          GRGIT_PASS: ${{secrets.GITHUB_TOKEN}}
        run: ./gradlew publish --scan --stacktrace
